require 'rubygems'
require 'active_support'
require 'active_support/core_ext'
require 'minitest/autorun'
require 'json'
require 'turn'
require 'minitest/unit'
require 'minitest-spec-context'
require 'mocha/setup'
require 'pry'

require 'how_slow'
