require 'how_slow/version'
require 'how_slow/setup'
require 'how_slow/collector'
require 'how_slow/reporter'
require 'how_slow/mailer'
require 'how_slow/metrics/base'
require 'how_slow/metrics/action'
require 'how_slow/metrics/counter'
